name: 'Docker build and push'
description: 'Docker build and push image to registry'
inputs:
  REGISTRY:
    description: ''
    required: true
  REGISTRY_USER:
    description: ''
    required: true
  REGISTRY_PASS:
    description: ''
    required: true
  IMAGE_NAME:
    description: ''
    required: true
  ARGS:
    description: 'Define additional groups here for building the image. e.g.: --target prod --build-arg key=value'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Docker Login
      run: echo ${{ inputs.REGISTRY_PASS }} | docker login ${{ inputs.REGISTRY }} -u ${{ inputs.REGISTRY_USER }} --password-stdin
      shell: bash
      
    - name: Build Docker Image
      run: docker build ${{ inputs.ARGS }} -t ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME}}:${{ github.sha }} .
      shell: bash
    
    - name: Push Docker Image
      run: docker push ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME}}:${{ github.sha }}
      shell: bash