name: 'Deploy to S3'
description: 'Deploy to S3'
inputs:
  bucket:
    description: 'Bucket name'
    required: true
  webname:
    description: 'Web name'
    required: true
runs:
  using: composite
  steps:
    - name: Deploy to S3
      run: aws s3 cp ./ s3://${{ inputs.bucket }}/latest/${{ inputs.webname }}/ --recursive --acl public-read
      shell: bash