name: QA
on:
  workflow_call:
jobs:
  node-version:
    name: "Node Version"
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Node version
        id: extract_version
        uses: findme-tecnologia/gha-shared/actions/check-node-version@main
  audit:
    name: "Audit"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.qa.outputs.node-version }}
      - name: Install dependencies
        uses: findme-tecnologia/gha-shared/actions/cached-deps@main
      - name: Audit
        run: npm audit
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.qa.outputs.node-version }}
      - name: Install dependencies
        uses: findme-tecnologia/gha-shared/actions/cached-deps@main
      - name: Lint
        run: npm lint
  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.qa.outputs.node-version }}
      - name: Install dependencies
        uses: findme-tecnologia/gha-shared/actions/cached-deps@main
      - name: Test
        run: npm test        
