name: 'Check Node version'
description: 'Check the node version by comparing package.json and Dockerfile'
outputs:
  version:
    description: 'Node version'
    value: ${{ steps.extract_version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -oP 'node:[^\s]+' Dockerfile | cut -d ':' -f2 | head -n 1 | sed 's/-.*//')
        echo "::save-state name=version::$VERSION"
      shell: bash

    - name: Check Node Version in package.json
      run: |
        DOCKERFILE_NODE_VERSION=${{ steps.extract_version.outputs.version }}
        PACKAGE_NODE_VERSION=$(jq -r '.engines.node' package.json)
        if [[ "$DOCKERFILE_NODE_VERSION" != "$PACKAGE_NODE_VERSION" ]]; then
          echo "ERROR: The Node.js versions in the Dockerfile ($DOCKERFILE_NODE_VERSION) and package.json ($PACKAGE_NODE_VERSION) are different."
          exit 1
        fi
      shell: bash
