name: 'NPM Audit'
description: 'NPM Audit'
inputs:
  node-version:
    description: 'Node version'
    required: true
  force:
    description: 'NPM install with --force'
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: NPM Cached
      id: cache-nodemodules
      uses: findme-tecnologia/gha-shared/.github/actions/npm-cached@main
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        if [ ${{ inputs.force }} == "true" ]; then
          npm i --force
        else
          npm i
        fi
      shell: bash
    - name: Audit packages
      run: npm audit --audit-level moderate
      env:
        CI: "true"
      shell: bash
