name: QA
on:
  workflow_call:
jobs:
  node-version:
    name: "Extract Node Version"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && 
      (github.event.action == 'opened' || github.event.action == 'synchronize') && 
      github.event.pull_request.base.ref == 'main'
    outputs:
      node-version: ${{ steps.node-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract Node version
        id: node-version
        uses: findme-tecnologia/gha-shared/.github/actions/extract-node-version-from-package@main
  audit:
    name: "Audit"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Audit
        uses: findme-tecnologia/gha-shared/.github/actions/npm-audit@main
        with:
          node-version: ${{ needs.node-version.outputs.node-version }}
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Audit
        uses: findme-tecnologia/gha-shared/.github/actions/npm-lint@main
        with:
          node-version: ${{ needs.node-version.outputs.node-version }}
  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Test
        uses: findme-tecnologia/gha-shared/.github/actions/npm-test@main
        with:
          node-version: ${{ needs.node-version.outputs.node-version }}