name: QA
on:
  workflow_call:
    inputs:
      build:
        description: 'Use build step'
        required: false
        type: boolean
        default: true
    secrets:
      SLACK_WEBHOOK_URL:
        description: 'Slack Webhook URL'
        required: true
      SLACK_CHANNEL_ID:
        description: 'Slack Channel ID'
        required: true
jobs:
  node-version:
    name: "Node Version"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && 
      (github.event.action == 'opened' || github.event.action == 'synchronize') && 
      github.event.pull_request.base.ref == 'main'
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Node version
        id: extract_version
        uses: findme-tecnologia/gha-shared/.github/actions/check-node-version@main
  audit:
    name: "Audit"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Audit
        uses: findme-tecnologia/gha-shared/.github/actions/npm-audit@main
        with:
          node-version: ${{ needs.node-version.outputs.version }}
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Lint
        uses: findme-tecnologia/gha-shared/.github/actions/npm-lint@main
        with:
          node-version: ${{ needs.node-version.outputs.version }}
  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: node-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Test
        uses: findme-tecnologia/gha-shared/.github/actions/npm-test@main
        with:
          node-version: ${{ needs.node-version.outputs.version }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: node-version
    if: ${{ inputs.build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Build
        uses: findme-tecnologia/gha-shared/.github/actions/npm-build@main
        with:
          node-version: ${{ needs.node-version.outputs.version }}

  notify_slack:
    name: "Notify Slack"
    runs-on: ubuntu-latest
    needs: [node-version, audit, lint, test, build]
    if: always()
    steps:
      - name: Check if any job failed
        id: check_failure
        run: |
          if [[ "${{ needs.node-version.result }}" == "failure" ]] || \
              [[ "${{ needs.audit.result }}" == "failure" ]] || \
              [[ "${{ needs.lint.result }}" == "failure" ]] || \
              [[ "${{ needs.test.result }}" == "failure" ]] || \
              [[ "${{ needs.build.result }}" == "failure" ]]; then
            echo "failure=true" >> $GITHUB_ENV
          else
            echo "failure=false" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Notify Slack on Failure
        if: ${{ env.failure == 'true' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data \
            '{
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "Falha no pipeline de QA:\n*Repo:* <${{ github.server_url }}/${{ github.repository }}> \n*Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
            }' \
            $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        shell: bash
